### ISSUE TITLE
[Question] Possible to use a second custom renderer ontop of XFG?

### ISSUE THREAD

**Issue by torrobinson** [tbaggett/xfgloss#27]
I spent a while debugging why a new `SwitchCellRenderer` wasn't working and have discovered that it was because XFG has registered its own (I wasn't using it for the SwitchCells and wasn't aware it affected them).

Now that I'm aware that I, if anything, should be creating a subclass of `XFGlossSwitchCellRenderer`, how about do I go applying it to `SwitchCells`? Is there any way I can tell XFG to use a new subclass of `XFGlossSwitchCellRenderer` rather than the default `XFGlossSwitchCellRenderer`? 

I'm just looking to tweak something subtle about `SwitchCells` (padding, nothing too crazy).

Thanks!

I am creating a new renderer as such:
```
public class PCLSwitchCellRenderer : XFGlossSwitchCellRenderer
    {
        public override UITableViewCell GetCell(Cell item, UITableViewCell reusableCell, UITableView tv)
        {
            UITableViewCell cell = base.GetCell(item, reusableCell, tv);
            if (cell != null)
            {
                // tweak my switchcell here...
                cell.TextLabel.Text = "test test test";
            }

            return cell;
        }
    }
```

**Comment by tbaggett** [comment]
Hi @torrobinson, using other custom renderers is documented in the readme at https://github.com/tbaggett/xfgloss#using-xfgloss-with-other-custom-xf-controls. 

I think you can do what you want by creating a new Xamarin.Forms control class that extends the Xamarin.Forms.SwitchCell class, then assigning your custom renderer (which should still extend the XFGlossSwitchCellRenderer class) as its renderer. You will then use your custom SwitchCell-derived class instead of the stock one in your XF layouts.

Cross-platform class:

```
public class MySwitchCell : Xamarin.Forms.SwitchCell { }
```

Map your iOS custom renderer to the new SwitchCell-derived class using the ExportRenderer assembly attribute. This is the important part, as it tells Xamarin.Forms which renderer to use for a Xamarin.Forms control.

```
[assembly: ExportRenderer(typeof(MySwitchCell), typeof(PCLSwitchCellRenderer))]
namespace MyCustomNameSpace.iOS
{
    public class PCLSwitchCellRenderer : XFGlossSwitchCellRenderer
    {
```

Please give that a try. Get back to me if it doesn't work and I will try to help you out. Otherwise, please close this issue if it takes care of it. Thanks for using XFGloss!

**Comment by torrobinson** [comment]
Thanks @tbaggett, this should work - I was hoping to avoid replacing all my switchcells with a custom class, but it's not the end of the world. I'll try this now! Thanks for making XFGloss!
