### ISSUE TITLE
Failed to add reference. The package 'Ansuria.XFGloss' tried to add a framework reference to 'System.Collections'

### ISSUE THREAD

**Issue by jcesarmm** [tbaggett/xfgloss#30]
Hi,

I get this error when I try to install the package  v1.1.3 into my Android project

"Failed to add reference. The package 'Ansuria.XFGloss' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance."

Thank you for your assistance...

Regards,

Julio

**Comment by tbaggett** [comment]
Sorry for the slow reply. My father was ill through most of the summer before passing away at the end of August. 

I attempted to recreate your issue in a new, blank Xamarin.Forms project, commonly referred to as the "Welcome to Xamarin.Forms!" starter project. I saw some warnings for some Android resources due to XF v3.1.0.697729 being used in the project while XFGloss v1.1.3 was built with XF v2.5.0.280555, but didn't see the error that you reported. 

Can you provide any further details? Thank you.

`1>------ Rebuild All started: Project: XFGTest, Configuration: Debug Any CPU ------
1>XFGTest -> C:\Users\me\Projects\Test\XFGTest\XFGTest\XFGTest\bin\Debug\netstandard2.0\XFGTest.dll
2>------ Rebuild All started: Project: XFGTest.Android, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Animation.design_fab_in. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Animation.design_fab_out. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Color.abc_tint_switch_thumb. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Color.design_textinput_error_color_dark. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Color.design_textinput_error_color_light. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Layout.abc_action_bar_view_list_nav_layout. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.String.abc_action_bar_home_description_format. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.String.abc_action_bar_home_subtitle_description_format. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.String.library_name. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_AppCompat_Notification. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Info. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Info_Media. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Line2. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Line2_Media. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Media. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Time. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Time_Media. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Title. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Title_Media. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_StatusBar_EventContent. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_StatusBar_EventContent_Info. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_StatusBar_EventContent_Line2. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_StatusBar_EventContent_Time. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.TextAppearance_StatusBar_EventContent_Title. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.Widget_AppCompat_NotificationActionContainer. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Style.Widget_AppCompat_NotificationActionText. Please check that your Nuget Package versions are compatible.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1715,2): warning XA0106: Skipping XFGTest.Droid.Resource.Styleable.MediaRouteButton_buttonTint. Please check that your Nuget Package versions are compatible.
2>  XFGTest.Android -> C:\Users\me\Projects\Test\XFGTest\XFGTest\XFGTest.Android\bin\Debug\XFGTest.Android.dll
2>  No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========
`

**Comment by jcesarmm** [comment]
Hi @tbaggett ,

So sorry to hear it and I hope your father feels well...

I have migrated the project from PCL to .NET Standard and I don't see the error, So I think the error was related with PCL Libraries I was using Profile259

Regards,

Julio

**Comment by tbaggett** [comment]
Hi @jcesarmm, thanks for the follow up. I'm happy to hear you got it resolved.

**Comment by ergodaveh** [comment]
This error message has appeared today while attempting to add the package v1.1.3 to eSHopOnContainers MobileApps using the most  updated  Xamarin Forms 3.4. 

 Failed to add reference. The package 'Ansuria.XFGloss' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Reference unavailable.
