### ISSUE TITLE
Type xfg:ContentPageGloss.BackgroundGradient not found

### ISSUE THREAD

**Issue by nodoid** [tbaggett/xfgloss#32]
I'm following the example on the example project, but when I try to compile I get the error that xfg:ContentPageGloss.BackgroundGradient not found in xmlns car-namespace:XFGloss;assembly=XFGloss

My full xaml page is

<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="TruckWiz.UI.LoginPage" xmlns:xfg="clr-namespace:XFGloss;assembly=XFGloss" Padding="12">
	<ContentPage.Content>
		<xfg:ContentPageGloss.BackgroundGradient>
        <xfg:Gradient Rotation="180">
            <xfg:GradientStep StepColor="#f4cf86" StepPercentage="0" />
            <xfg:GradientStep StepColor="#b5c89a" StepPercentage=".5" />
            <xfg:GradientStep StepColor="#77c2ae" StepPercentage="1" />
        </xfg:Gradient>
    </xfg:ContentPageGloss.BackgroundGradient>
	</ContentPage.Content>
</ContentPage>

I have XFGloss initialised in both the Android and iOS projects with the target framework set to .NET Standard 2.

I don't have a problem if I'm writing code rather than xaml

**Comment by pdonovan** [comment]
I'm having the same problem. I've downloaded and built the sample app. That works fine. But as soon as you edit AboutPage.xaml to wrap the `xfg:ContentPageGloss.BackgroundGradient` in a `ContentPage.Content` element (common practice on real-world apps) the error appears. I've yet to find a solution.

**Comment by tbaggett** [comment]
Sorry for the slow reply. My father was ill through most of the summer before passing away at the end of August. 

I respectfully disagree that wrapping a page's content in a <ContentPage.Content> element is a common practice in real-world apps.  I've built a number of commercial apps using Xamarin.Forms, as well as reviewed apps authored by others, and that hasn't been my experience at least.  The official [ContentPropertyAttribute class documentation](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.contentpropertyattribute?view=xamarin-forms) also doesn't indicate it is required, or even necessarily recommended/preferred, to be explicitly declared.

In regards to the specific issue you're seeing, it is due to the ContentPage's Content property being declared as type View. You can confirm this by viewing the [ContentPage source on GitHub](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ContentPage.cs). Therefore, only classes that derive from the View class can be assigned to the ContentPage's Content property.

I hope this info was helpful and, again, apologies that it took so long to reply.
