### ISSUE TITLE
XFGloss Gradient not working in Release mode for iOS with "Link SDK Assemblies only"

### ISSUE THREAD

**Issue by gtbuchanan** [tbaggett/xfgloss#8]
I have tried every manner of configuration I could think of to get this working. I'm only using a `Gradient` with `ContentPageGloss.BackgroundGradient` in XAML, but it refuses to render in Release mode with iOS "Linker Behavior" set to "Link SDK Assemblies only". I have tried all of the following, to no avail:

1. Standard `XFGloss.iOS.Library.Init()` call in AppDelegate
2. Reference `Gradient` and `ContentPageGloss` classes in preservation class (Similar to how Akavache suggests [here][0]).
3. mtouch arguments `--linkskip=XFGloss --linkskip=XFGloss.iOS`

Any ideas?

[0]: https://github.com/akavache/Akavache/blob/akavache5-master/src/Akavache.Sqlite3/content/AkavacheSqliteLinkerOverride.cs.pp

**Comment by tbaggett** [comment]
Hi Taylor,

I will try to reproduce the issue and get back to you.

**Comment by tbaggett** [comment]
I have reproduced the issue. Investigating it now.

**Comment by gtbuchanan** [comment]
I was putting together a repro project, but you responded faster than I was able to. Thanks for the great support!

**Comment by tbaggett** [comment]
You're welcome! I'm currently between jobs and have lots of free time on my hands unfortunately, haha. 

I have built a new version that fixed the issue in my testing. It is available through my CI deployment to myGet - http://myget.org/feed/ansuria-ci/package/nuget/Ansuria.XFGloss. 

Can you add MyGet to your NuGet sources and try the v1.0.4.37 package? In Xamarin Studio on the Mac, open preferences and navigate to NuGet - Sources. Add "https://www.myget.org/F/ansuria-ci/api/v2" as a new source. Visual Studio should offer similar options if you're using that instead. 

Once the path is added, you should see an update is available for XFGloss. Please update the package in both your PCL and iOS projects, then perform a full rebuild, before testing.

I will push a new release to NuGet once you've verified the issue is fixed. Thanks for reporting it!

**Comment by gtbuchanan** [comment]
The issue appears to be resolved now. Thank you, sir! Also, great job filling in the gaps with Xamarin styling.

**Comment by tbaggett** [comment]
Awesome, happy to hear it! I will push a new release to GitHub. And thanks for the kind words. Have a great weekend.
